apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: .endjin/devcontainer/ai-agent
  contents:
  - git:
      url: https://github.com/endjin/ai-agent-devcontainer.git
      ref: main
    path: .
    includePaths:
    - .devcontainer/**/*
