[project]
name = "endjin-polars-examples"
version = "0.1.0"
description = "Open source examples for data engineering with Polars."
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "polars",
    "requests",
    "pyarrow",
    "fsspec",
    "deltalake",
    "pandera[polars]",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "plotly[express]",
    "nbformat",
    "nbconvert",
    "xlsxwriter",
    "duckdb",
    "pandas",
    "behave",
    "pytest",
    "black",
    "flake8"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_importers", "src/data_wrangler"]
